// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file etcd/api/etcdserverpb/etcdserver.proto (package etcdserverpb, syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file etcd/api/etcdserverpb/etcdserver.proto.
 */
export const file_etcd_api_etcdserverpb_etcdserver: GenFile = /*@__PURE__*/
  fileDesc("CiZldGNkL2FwaS9ldGNkc2VydmVycGIvZXRjZHNlcnZlci5wcm90bxIMZXRjZHNlcnZlcnBiIv8CCgdSZXF1ZXN0EhAKAklEGAEgASgEQgTI3h8AEhQKBk1ldGhvZBgCIAEoCUIEyN4fABISCgRQYXRoGAMgASgJQgTI3h8AEhEKA1ZhbBgEIAEoCUIEyN4fABIRCgNEaXIYBSABKAhCBMjeHwASFwoJUHJldlZhbHVlGAYgASgJQgTI3h8AEhcKCVByZXZJbmRleBgHIAEoBEIEyN4fABIXCglQcmV2RXhpc3QYCCABKAhCBMjeHwESGAoKRXhwaXJhdGlvbhgJIAEoA0IEyN4fABISCgRXYWl0GAogASgIQgTI3h8AEhMKBVNpbmNlGAsgASgEQgTI3h8AEhcKCVJlY3Vyc2l2ZRgMIAEoCEIEyN4fABIUCgZTb3J0ZWQYDSABKAhCBMjeHwASFAoGUXVvcnVtGA4gASgIQgTI3h8AEhIKBFRpbWUYDyABKANCBMjeHwASFAoGU3RyZWFtGBAgASgIQgTI3h8AEhUKB1JlZnJlc2gYESABKAhCBMjeHwEiOQoITWV0YWRhdGESFAoGTm9kZUlEGAEgASgEQgTI3h8AEhcKCUNsdXN0ZXJJRBgCIAEoBEIEyN4fAEI1WiNnby5ldGNkLmlvL2V0Y2QvYXBpL3YzL2V0Y2RzZXJ2ZXJwYsjhHgDI4h4B0OIeAeDiHgE", [file_gogoproto_gogo]);

/**
 * @generated from message etcdserverpb.Request
 */
export type Request = Message<"etcdserverpb.Request"> & {
  /**
   * @generated from field: optional uint64 ID = 1;
   */
  ID: bigint;

  /**
   * @generated from field: optional string Method = 2;
   */
  Method: string;

  /**
   * @generated from field: optional string Path = 3;
   */
  Path: string;

  /**
   * @generated from field: optional string Val = 4;
   */
  Val: string;

  /**
   * @generated from field: optional bool Dir = 5;
   */
  Dir: boolean;

  /**
   * @generated from field: optional string PrevValue = 6;
   */
  PrevValue: string;

  /**
   * @generated from field: optional uint64 PrevIndex = 7;
   */
  PrevIndex: bigint;

  /**
   * @generated from field: optional bool PrevExist = 8;
   */
  PrevExist: boolean;

  /**
   * @generated from field: optional int64 Expiration = 9;
   */
  Expiration: bigint;

  /**
   * @generated from field: optional bool Wait = 10;
   */
  Wait: boolean;

  /**
   * @generated from field: optional uint64 Since = 11;
   */
  Since: bigint;

  /**
   * @generated from field: optional bool Recursive = 12;
   */
  Recursive: boolean;

  /**
   * @generated from field: optional bool Sorted = 13;
   */
  Sorted: boolean;

  /**
   * @generated from field: optional bool Quorum = 14;
   */
  Quorum: boolean;

  /**
   * @generated from field: optional int64 Time = 15;
   */
  Time: bigint;

  /**
   * @generated from field: optional bool Stream = 16;
   */
  Stream: boolean;

  /**
   * @generated from field: optional bool Refresh = 17;
   */
  Refresh: boolean;
};

/**
 * Describes the message etcdserverpb.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export const RequestSchema: GenMessage<Request> = /*@__PURE__*/
  messageDesc(file_etcd_api_etcdserverpb_etcdserver, 0);

/**
 * @generated from message etcdserverpb.Metadata
 */
export type Metadata = Message<"etcdserverpb.Metadata"> & {
  /**
   * @generated from field: optional uint64 NodeID = 1;
   */
  NodeID: bigint;

  /**
   * @generated from field: optional uint64 ClusterID = 2;
   */
  ClusterID: bigint;
};

/**
 * Describes the message etcdserverpb.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> = /*@__PURE__*/
  messageDesc(file_etcd_api_etcdserverpb_etcdserver, 1);

