// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file etcd/api/mvccpb/kv.proto (package mvccpb, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file etcd/api/mvccpb/kv.proto.
 */
export const file_etcd_api_mvccpb_kv: GenFile = /*@__PURE__*/
  fileDesc("ChhldGNkL2FwaS9tdmNjcGIva3YucHJvdG8SBm12Y2NwYiJ1CghLZXlWYWx1ZRILCgNrZXkYASABKAwSFwoPY3JlYXRlX3JldmlzaW9uGAIgASgDEhQKDG1vZF9yZXZpc2lvbhgDIAEoAxIPCgd2ZXJzaW9uGAQgASgDEg0KBXZhbHVlGAUgASgMEg0KBWxlYXNlGAYgASgDIpEBCgVFdmVudBIlCgR0eXBlGAEgASgOMhcubXZjY3BiLkV2ZW50LkV2ZW50VHlwZRIcCgJrdhgCIAEoCzIQLm12Y2NwYi5LZXlWYWx1ZRIhCgdwcmV2X2t2GAMgASgLMhAubXZjY3BiLktleVZhbHVlIiAKCUV2ZW50VHlwZRIHCgNQVVQQABIKCgZERUxFVEUQAUIzWh1nby5ldGNkLmlvL2V0Y2QvYXBpL3YzL212Y2NwYsjhHgDQ4R4AyOIeAdDiHgHg4h4BYgZwcm90bzM", [file_gogoproto_gogo]);

/**
 * @generated from message mvccpb.KeyValue
 */
export type KeyValue = Message<"mvccpb.KeyValue"> & {
  /**
   * key is the key in bytes. An empty key is not allowed.
   *
   * @generated from field: bytes key = 1;
   */
  key: Uint8Array;

  /**
   * create_revision is the revision of last creation on this key.
   *
   * @generated from field: int64 create_revision = 2;
   */
  createRevision: bigint;

  /**
   * mod_revision is the revision of last modification on this key.
   *
   * @generated from field: int64 mod_revision = 3;
   */
  modRevision: bigint;

  /**
   * version is the version of the key. A deletion resets
   * the version to zero and any modification of the key
   * increases its version.
   *
   * @generated from field: int64 version = 4;
   */
  version: bigint;

  /**
   * value is the value held by the key, in bytes.
   *
   * @generated from field: bytes value = 5;
   */
  value: Uint8Array;

  /**
   * lease is the ID of the lease that attached to key.
   * When the attached lease expires, the key will be deleted.
   * If lease is 0, then no lease is attached to the key.
   *
   * @generated from field: int64 lease = 6;
   */
  lease: bigint;
};

/**
 * Describes the message mvccpb.KeyValue.
 * Use `create(KeyValueSchema)` to create a new message.
 */
export const KeyValueSchema: GenMessage<KeyValue> = /*@__PURE__*/
  messageDesc(file_etcd_api_mvccpb_kv, 0);

/**
 * @generated from message mvccpb.Event
 */
export type Event = Message<"mvccpb.Event"> & {
  /**
   * type is the kind of event. If type is a PUT, it indicates
   * new data has been stored to the key. If type is a DELETE,
   * it indicates the key was deleted.
   *
   * @generated from field: mvccpb.Event.EventType type = 1;
   */
  type: Event_EventType;

  /**
   * kv holds the KeyValue for the event.
   * A PUT event contains current kv pair.
   * A PUT event with kv.Version=1 indicates the creation of a key.
   * A DELETE/EXPIRE event contains the deleted key with
   * its modification revision set to the revision of deletion.
   *
   * @generated from field: mvccpb.KeyValue kv = 2;
   */
  kv?: KeyValue;

  /**
   * prev_kv holds the key-value pair before the event happens.
   *
   * @generated from field: mvccpb.KeyValue prev_kv = 3;
   */
  prevKv?: KeyValue;
};

/**
 * Describes the message mvccpb.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_etcd_api_mvccpb_kv, 1);

/**
 * @generated from enum mvccpb.Event.EventType
 */
export enum Event_EventType {
  /**
   * @generated from enum value: PUT = 0;
   */
  PUT = 0,

  /**
   * @generated from enum value: DELETE = 1;
   */
  DELETE = 1,
}

/**
 * Describes the enum mvccpb.Event.EventType.
 */
export const Event_EventTypeSchema: GenEnum<Event_EventType> = /*@__PURE__*/
  enumDesc(file_etcd_api_mvccpb_kv, 1, 0);

