// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file etcd/api/authpb/auth.proto (package authpb, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file etcd/api/authpb/auth.proto.
 */
export const file_etcd_api_authpb_auth: GenFile = /*@__PURE__*/
  fileDesc("ChpldGNkL2FwaS9hdXRocGIvYXV0aC5wcm90bxIGYXV0aHBiIiUKDlVzZXJBZGRPcHRpb25zEhMKC25vX3Bhc3N3b3JkGAEgASgIIl4KBFVzZXISDAoEbmFtZRgBIAEoDBIQCghwYXNzd29yZBgCIAEoDBINCgVyb2xlcxgDIAMoCRInCgdvcHRpb25zGAQgASgLMhYuYXV0aHBiLlVzZXJBZGRPcHRpb25zIoMBCgpQZXJtaXNzaW9uEikKCHBlcm1UeXBlGAEgASgOMhcuYXV0aHBiLlBlcm1pc3Npb24uVHlwZRILCgNrZXkYAiABKAwSEQoJcmFuZ2VfZW5kGAMgASgMIioKBFR5cGUSCAoEUkVBRBAAEgkKBVdSSVRFEAESDQoJUkVBRFdSSVRFEAIiPwoEUm9sZRIMCgRuYW1lGAEgASgMEikKDWtleVBlcm1pc3Npb24YAiADKAsyEi5hdXRocGIuUGVybWlzc2lvbkIzWh1nby5ldGNkLmlvL2V0Y2QvYXBpL3YzL2F1dGhwYsjhHgDQ4R4AyOIeAdDiHgHg4h4BYgZwcm90bzM", [file_gogoproto_gogo]);

/**
 * @generated from message authpb.UserAddOptions
 */
export type UserAddOptions = Message<"authpb.UserAddOptions"> & {
  /**
   * @generated from field: bool no_password = 1;
   */
  noPassword: boolean;
};

/**
 * Describes the message authpb.UserAddOptions.
 * Use `create(UserAddOptionsSchema)` to create a new message.
 */
export const UserAddOptionsSchema: GenMessage<UserAddOptions> = /*@__PURE__*/
  messageDesc(file_etcd_api_authpb_auth, 0);

/**
 * User is a single entry in the bucket authUsers
 *
 * @generated from message authpb.User
 */
export type User = Message<"authpb.User"> & {
  /**
   * @generated from field: bytes name = 1;
   */
  name: Uint8Array;

  /**
   * @generated from field: bytes password = 2;
   */
  password: Uint8Array;

  /**
   * @generated from field: repeated string roles = 3;
   */
  roles: string[];

  /**
   * @generated from field: authpb.UserAddOptions options = 4;
   */
  options?: UserAddOptions;
};

/**
 * Describes the message authpb.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_etcd_api_authpb_auth, 1);

/**
 * Permission is a single entity
 *
 * @generated from message authpb.Permission
 */
export type Permission = Message<"authpb.Permission"> & {
  /**
   * @generated from field: authpb.Permission.Type permType = 1;
   */
  permType: Permission_Type;

  /**
   * @generated from field: bytes key = 2;
   */
  key: Uint8Array;

  /**
   * @generated from field: bytes range_end = 3;
   */
  rangeEnd: Uint8Array;
};

/**
 * Describes the message authpb.Permission.
 * Use `create(PermissionSchema)` to create a new message.
 */
export const PermissionSchema: GenMessage<Permission> = /*@__PURE__*/
  messageDesc(file_etcd_api_authpb_auth, 2);

/**
 * @generated from enum authpb.Permission.Type
 */
export enum Permission_Type {
  /**
   * @generated from enum value: READ = 0;
   */
  READ = 0,

  /**
   * @generated from enum value: WRITE = 1;
   */
  WRITE = 1,

  /**
   * @generated from enum value: READWRITE = 2;
   */
  READWRITE = 2,
}

/**
 * Describes the enum authpb.Permission.Type.
 */
export const Permission_TypeSchema: GenEnum<Permission_Type> = /*@__PURE__*/
  enumDesc(file_etcd_api_authpb_auth, 2, 0);

/**
 * Role is a single entry in the bucket authRoles
 *
 * @generated from message authpb.Role
 */
export type Role = Message<"authpb.Role"> & {
  /**
   * @generated from field: bytes name = 1;
   */
  name: Uint8Array;

  /**
   * @generated from field: repeated authpb.Permission keyPermission = 2;
   */
  keyPermission: Permission[];
};

/**
 * Describes the message authpb.Role.
 * Use `create(RoleSchema)` to create a new message.
 */
export const RoleSchema: GenMessage<Role> = /*@__PURE__*/
  messageDesc(file_etcd_api_authpb_auth, 3);

