// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file etcd/api/membershippb/membership.proto (package membershippb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import { file_etcd_api_versionpb_version } from "../versionpb/version_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file etcd/api/membershippb/membership.proto.
 */
export const file_etcd_api_membershippb_membership: GenFile = /*@__PURE__*/
  fileDesc("CiZldGNkL2FwaS9tZW1iZXJzaGlwcGIvbWVtYmVyc2hpcC5wcm90bxIMbWVtYmVyc2hpcHBiIkAKDlJhZnRBdHRyaWJ1dGVzEhEKCXBlZXJfdXJscxgBIAMoCRISCgppc19sZWFybmVyGAIgASgIOgeCtRgDMy41IjgKCkF0dHJpYnV0ZXMSDAoEbmFtZRgBIAEoCRITCgtjbGllbnRfdXJscxgCIAMoCToHgrUYAzMuNSKJAQoGTWVtYmVyEgoKAklEGAEgASgEEjUKD3JhZnRfYXR0cmlidXRlcxgCIAEoCzIcLm1lbWJlcnNoaXBwYi5SYWZ0QXR0cmlidXRlcxIzChFtZW1iZXJfYXR0cmlidXRlcxgDIAEoCzIYLm1lbWJlcnNoaXBwYi5BdHRyaWJ1dGVzOgeCtRgDMy41IjAKGENsdXN0ZXJWZXJzaW9uU2V0UmVxdWVzdBILCgN2ZXIYASABKAk6B4K1GAMzLjUibgobQ2x1c3Rlck1lbWJlckF0dHJTZXRSZXF1ZXN0EhEKCW1lbWJlcl9JRBgBIAEoBBIzChFtZW1iZXJfYXR0cmlidXRlcxgCIAEoCzIYLm1lbWJlcnNoaXBwYi5BdHRyaWJ1dGVzOgeCtRgDMy41IkAKF0Rvd25ncmFkZUluZm9TZXRSZXF1ZXN0Eg8KB2VuYWJsZWQYASABKAgSCwoDdmVyGAIgASgJOgeCtRgDMy41QjVaI2dvLmV0Y2QuaW8vZXRjZC9hcGkvdjMvbWVtYmVyc2hpcHBiyOEeAMjiHgHQ4h4B4OIeAWIGcHJvdG8z", [file_gogoproto_gogo, file_etcd_api_versionpb_version]);

/**
 * RaftAttributes represents the raft related attributes of an etcd member.
 *
 * @generated from message membershippb.RaftAttributes
 */
export type RaftAttributes = Message<"membershippb.RaftAttributes"> & {
  /**
   * peerURLs is the list of peers in the raft cluster.
   *
   * @generated from field: repeated string peer_urls = 1;
   */
  peerUrls: string[];

  /**
   * isLearner indicates if the member is raft learner.
   *
   * @generated from field: bool is_learner = 2;
   */
  isLearner: boolean;
};

/**
 * Describes the message membershippb.RaftAttributes.
 * Use `create(RaftAttributesSchema)` to create a new message.
 */
export const RaftAttributesSchema: GenMessage<RaftAttributes> = /*@__PURE__*/
  messageDesc(file_etcd_api_membershippb_membership, 0);

/**
 * Attributes represents all the non-raft related attributes of an etcd member.
 *
 * @generated from message membershippb.Attributes
 */
export type Attributes = Message<"membershippb.Attributes"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: repeated string client_urls = 2;
   */
  clientUrls: string[];
};

/**
 * Describes the message membershippb.Attributes.
 * Use `create(AttributesSchema)` to create a new message.
 */
export const AttributesSchema: GenMessage<Attributes> = /*@__PURE__*/
  messageDesc(file_etcd_api_membershippb_membership, 1);

/**
 * @generated from message membershippb.Member
 */
export type Member = Message<"membershippb.Member"> & {
  /**
   * @generated from field: uint64 ID = 1;
   */
  ID: bigint;

  /**
   * @generated from field: membershippb.RaftAttributes raft_attributes = 2;
   */
  raftAttributes?: RaftAttributes;

  /**
   * @generated from field: membershippb.Attributes member_attributes = 3;
   */
  memberAttributes?: Attributes;
};

/**
 * Describes the message membershippb.Member.
 * Use `create(MemberSchema)` to create a new message.
 */
export const MemberSchema: GenMessage<Member> = /*@__PURE__*/
  messageDesc(file_etcd_api_membershippb_membership, 2);

/**
 * @generated from message membershippb.ClusterVersionSetRequest
 */
export type ClusterVersionSetRequest = Message<"membershippb.ClusterVersionSetRequest"> & {
  /**
   * @generated from field: string ver = 1;
   */
  ver: string;
};

/**
 * Describes the message membershippb.ClusterVersionSetRequest.
 * Use `create(ClusterVersionSetRequestSchema)` to create a new message.
 */
export const ClusterVersionSetRequestSchema: GenMessage<ClusterVersionSetRequest> = /*@__PURE__*/
  messageDesc(file_etcd_api_membershippb_membership, 3);

/**
 * @generated from message membershippb.ClusterMemberAttrSetRequest
 */
export type ClusterMemberAttrSetRequest = Message<"membershippb.ClusterMemberAttrSetRequest"> & {
  /**
   * @generated from field: uint64 member_ID = 1;
   */
  memberID: bigint;

  /**
   * @generated from field: membershippb.Attributes member_attributes = 2;
   */
  memberAttributes?: Attributes;
};

/**
 * Describes the message membershippb.ClusterMemberAttrSetRequest.
 * Use `create(ClusterMemberAttrSetRequestSchema)` to create a new message.
 */
export const ClusterMemberAttrSetRequestSchema: GenMessage<ClusterMemberAttrSetRequest> = /*@__PURE__*/
  messageDesc(file_etcd_api_membershippb_membership, 4);

/**
 * @generated from message membershippb.DowngradeInfoSetRequest
 */
export type DowngradeInfoSetRequest = Message<"membershippb.DowngradeInfoSetRequest"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * @generated from field: string ver = 2;
   */
  ver: string;
};

/**
 * Describes the message membershippb.DowngradeInfoSetRequest.
 * Use `create(DowngradeInfoSetRequestSchema)` to create a new message.
 */
export const DowngradeInfoSetRequestSchema: GenMessage<DowngradeInfoSetRequest> = /*@__PURE__*/
  messageDesc(file_etcd_api_membershippb_membership, 5);

