// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file etcd/api/versionpb/version.proto (package versionpb, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv1";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { EnumOptions, EnumValueOptions, FieldOptions, MessageOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file etcd/api/versionpb/version.proto.
 */
export const file_etcd_api_versionpb_version: GenFile = /*@__PURE__*/
  fileDesc("CiBldGNkL2FwaS92ZXJzaW9ucGIvdmVyc2lvbi5wcm90bxIJdmVyc2lvbnBiOk4KEGV0Y2RfdmVyc2lvbl9tc2cSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMY0IYDIAEoCVIOZXRjZFZlcnNpb25Nc2eIAQE6UAoSZXRjZF92ZXJzaW9uX2ZpZWxkEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjRhgMgASgJUhBldGNkVmVyc2lvbkZpZWxkiAEBOk0KEWV0Y2RfdmVyc2lvbl9lbnVtEhwuZ29vZ2xlLnByb3RvYnVmLkVudW1PcHRpb25zGNKGAyABKAlSD2V0Y2RWZXJzaW9uRW51bYgBATpdChdldGNkX3ZlcnNpb25fZW51bV92YWx1ZRIhLmdvb2dsZS5wcm90b2J1Zi5FbnVtVmFsdWVPcHRpb25zGNOGAyABKAlSFGV0Y2RWZXJzaW9uRW51bVZhbHVliAEBQipaIGdvLmV0Y2QuaW8vZXRjZC9hcGkvdjMvdmVyc2lvbnBiyOIeAdDiHgFiBnByb3RvMw", [file_gogoproto_gogo, file_google_protobuf_descriptor]);

/**
 * @generated from extension: optional string etcd_version_msg = 50000;
 */
export const etcd_version_msg: GenExtension<MessageOptions, string> = /*@__PURE__*/
  extDesc(file_etcd_api_versionpb_version, 0);

/**
 * @generated from extension: optional string etcd_version_field = 50001;
 */
export const etcd_version_field: GenExtension<FieldOptions, string> = /*@__PURE__*/
  extDesc(file_etcd_api_versionpb_version, 1);

/**
 * @generated from extension: optional string etcd_version_enum = 50002;
 */
export const etcd_version_enum: GenExtension<EnumOptions, string> = /*@__PURE__*/
  extDesc(file_etcd_api_versionpb_version, 2);

/**
 * @generated from extension: optional string etcd_version_enum_value = 50003;
 */
export const etcd_version_enum_value: GenExtension<EnumValueOptions, string> = /*@__PURE__*/
  extDesc(file_etcd_api_versionpb_version, 3);

